<?php

namespace Wits\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImportantDatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportantDatesRepository extends EntityRepository
{

    public function getImportanteDateByConferenceEdition($edition){
        return $this->createQueryBuilder('d')
            ->join('d.conference', 'c')
            ->where('c.edition = :edition ')
            ->setParameter('edition', $edition)
            ->getQuery()
            ->getResult();
    }

}
