<?php

namespace Wits\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
    public function getPulictionsByConferenceEdition($edition){
        return $this->createQueryBuilder('p')
            ->join('p.conference', 'c')
            ->where('c.edition = :edition AND p.online = :status ')
            ->setParameter('edition', $edition)
            ->setParameter('status', true)
            ->getQuery()
            ->getResult();
    }
}
