<?php

namespace Wits\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationRepository extends EntityRepository
{
    public function getRegistrationByConferenceEdition($edition){
        return $this->createQueryBuilder('r')
            ->join('r.conference', 'c')
            ->where('c.edition = :edition AND r.online = :status')
            ->setParameter('edition', $edition)
            ->setParameter('status', true)
            ->getQuery()
            ->getResult();
    }
}
