<?php

namespace Wits\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository
{
    public function getSliderByConferenceEdition($edition){
        return $this->createQueryBuilder('s')
            ->join('s.conference', 'c')
            ->where('c.edition = :edition ')
            ->setParameter('edition', $edition)
            ->getQuery()
            ->getResult();
    }
}
