<?php

namespace Wits\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubmissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubmissionsRepository extends EntityRepository
{
}
