sonata_admin:
    security:
        information:
            GUEST:    []
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title:      "%sonata_admin.title%"
    title_logo: "%sonata_admin.logo_title%"
    options:
        html5_validate: false # does not use html5 validation
        pager_links: 5 # pager max links to display

    templates:
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
            #- { position: right, type: sonata.block.service.text, settings: { content: "<div class='panel panel-default'><div class='panel-heading'><h3 class='panel-title'>Welcome!</h3></div><div class='panel-body'>You can customize this dashboard by editing the <code>sonata_admin.yml</code> file. The current dashboard presents the recent items from the NewsBundle and a non-statistical e-commerce information.</div></div>"} }
            - { position: right, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 7, mode: admin }}
            - { position: right, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 7, mode: admin }}
            - { position: right, type: sonata.block.service.rss, settings: { title: IEEE News, url: https://csdl.computer.org/rss/cise.xml, template: SonataAdminBundle:Block:block_rss_dashboard.html.twig }}

        groups:
            sonata.admin.group.conference:
                label:           Gestion de Conference
                label_catalogue: WitsFrontBundle
                icon:            '<i class="fa fa-dashboard"></i>'
                items:
                    - wits_front.admin.conference
                    - wits_front.admin.committee
                    - wits_front.admin.important_dates
                    - wits_front.admin.submissions
                    - wits_front.admin.program
                    - wits_front.admin.speakers
                    - wits_front.admin.publication
                    - wits_front.admin.registration
                    - wits_front.admin.informations
                    - wits_front.admin.sponsor
                    - wits_front.admin.slider

            sonata.admin.group.participant:
                label:           Gestion de Participant
                label_catalogue: WitsFrontBundle
                icon:            '<i class="fa fa-users"></i>'
                items:
                    - wits_front.admin.country
                    - wits_front.admin.city
                    - wits_front.admin.university
                    - wits_front.admin.school
                    - wits_front.admin.participant

            sonata.admin.group.news:
                label:           News
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-th"></i>'
                items:
                    - sonata.news.admin.comment
                    - sonata.news.admin.post

            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
                    - sonata.classification.admin.category
                    - sonata.classification.admin.tag
                    - sonata.classification.admin.collection
    assets:
        stylesheets:
            - assetic/sonata_formatter_css.css
            - assetic/sonata_jqueryui_css.css
            - bundles/sonataformatter/markitup/skins/sonata/style.css
            - bundles/sonataformatter/markitup/sets/markdown/style.css
            - bundles/sonataformatter/markitup/sets/html/style.css
            - bundles/sonataformatter/markitup/sets/textile/style.css
            - bundles/sonataadmin/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/ionicons.min.css
            - bundles/sonataadmin/vendor/AdminLTE/css/AdminLTE.css
            - bundles/sonataadmin/vendor/jqueryui/themes/flick/jquery-ui.min.css
            - bundles/sonataadmin/vendor/select2/select2.css
            - bundles/sonataadmin/vendor/select2/select2-bootstrap.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css

        javascripts:
            - assetic/sonata_admin_js.js
            - assetic/sonata_jqueryui_js.js
            - assetic/sonata_formatter_js.js
            - bundles/sonataformatter/vendor/ckeditor/ckeditor.js

            - bundles/sonataadmin/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.core.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.widget.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.mouse.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.draggable.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.droppable.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.resizable.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.selectable.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.sortable.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.accordion.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.autocomplete.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.button.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.datepicker.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.dialog.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-blind.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-bounce.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-clip.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-drop.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-explode.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-fade.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-fold.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-highlight.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-pulsate.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-scale.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-shake.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-slide.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-transfer.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.menu.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.position.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.progressbar.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.slider.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.spinner.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.tabs.js
            - bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.tooltip.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.js
            - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonataadmin/vendor/select2/select2.min.js
            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js
            - bundles/sonataformatter/vendor/ckeditor/ckeditor.js
            - bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
            - bundles/sonataformatter/markitup/sets/markdown/set.js
            - bundles/sonataformatter/markitup/sets/html/set.js
            - bundles/sonataformatter/markitup/sets/textile/set.js
            - bundles/sonatapage/sonata-page.back.js
