# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    wits.configurtion.admin.class: Wits\FrontBundle\Admin\ConfigurationAdmin
    wits.configurtion.entity.class: Wits\FrontBundle\Entity\Configuration


services: